"""vecindario nullable

Revision ID: 2066265f5223
Revises: ee3a7402e7b6
Create Date: 2024-10-21 16:33:44.542730

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2066265f5223'
down_revision = 'ee3a7402e7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.alter_column('id_vecindario',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.alter_column('id_vecindario',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
