"""empty message

Revision ID: 45d3ecae3f36
Revises: 8352352d233a
Create Date: 2024-11-17 14:41:19.785135

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '45d3ecae3f36'
down_revision = '8352352d233a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_expiry')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
