"""empty message

Revision ID: 5ae740ac2f58
Revises: 
Create Date: 2024-11-21 20:49:01.943059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ae740ac2f58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferencia', schema=None) as batch_op:
        batch_op.alter_column('tipo_subsidio',
               existing_type=sa.VARCHAR(length=15),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferencia', schema=None) as batch_op:
        batch_op.alter_column('tipo_subsidio',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
