"""Fixes to vivienda_id

Revision ID: 6ca39abc01ac
Revises: 2066265f5223
Create Date: 2024-10-21 17:29:11.537406

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6ca39abc01ac'
down_revision = '2066265f5223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
