"""usuario a vivienda

Revision ID: 986fb4a7cb11
Revises: 5ae740ac2f58
Create Date: 2024-11-27 18:57:02.274314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986fb4a7cb11'
down_revision = '5ae740ac2f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
