"""Aumento id Vivienda a 50

Revision ID: ee3a7402e7b6
Revises: 1f46fc452459
Create Date: 2024-10-21 16:23:34.734089

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ee3a7402e7b6'
down_revision = '1f46fc452459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.alter_column('id_vivienda',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
